# -*- coding: utf-8 -*-
"""Heart disease Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tt0zJO-CnID9fKdBk0vCJudcC8JC3xhB
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

heart_data=pd.read_csv('/content/heart_disease_data.csv')
heart_data.head()

heart_data.isnull().sum()

heart_data.value_counts('target')

heart_data.describe()

heart_data.shape

sns.countplot(x='target',data=heart_data)

plt.figure(figsize=(20,10))
sns.countplot(x='age',data=heart_data)

sns.displot(data=heart_data,x='age',hue='target')

X=heart_data.drop(columns='target',axis=1)
Y=heart_data['target']

print(X)
print(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

model=RandomForestClassifier()
model.fit(X_train,Y_train)

X_train_prediction=model.predict(X_train)
X_train_accuracy=accuracy_score(X_train_prediction,Y_train)
print(X_train_accuracy)

model.fit(X_test,Y_test)
X_test_prediction=model.predict(X_test)
X_test_accuracy=accuracy_score(X_test_prediction,Y_test)
print(X_test_accuracy)

input_data=(61,1,0,120,260,0,1,140,1,3.6,1,1,3)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

prediction=model.predict(input_data_reshaped)

print(prediction)

if(prediction[0]==0):
  print('The person does not have a heart disease')
else:
  print('The person has heart disease')

import pickle

filename = 'trained_model.sav'
pickle.dump(model, open(filename,'wb'))

loaded_model = pickle.load(open('trained_model.sav','rb'))

